version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: socialnet_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: socialnet
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
